on: push

name: containers

jobs:
  jupyter:
    name: Jupyter Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.7",]
        requirements: ["tu-nlp4web",]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: jupyter
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          tags: croydon/jupyter:python-${{ matrix.python-version }}-${{ matrix.requirements }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            REQUIREMENTS=${{ matrix.requirements }}
